// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/RolloCasanova/dispatch-workshop-4/model"
	mock "github.com/stretchr/testify/mock"
)

// EmployeeRedisService is an autogenerated mock type for the EmployeeRedisService type
type EmployeeRedisService struct {
	mock.Mock
}

// DeleteEmployeeByID provides a mock function with given fields: id
func (_m *EmployeeRedisService) DeleteEmployeeByID(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadEmployee provides a mock function with given fields: id
func (_m *EmployeeRedisService) ReadEmployee(id int) (*model.Employee, error) {
	ret := _m.Called(id)

	var r0 *model.Employee
	if rf, ok := ret.Get(0).(func(int) *model.Employee); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Employee)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertEmployee provides a mock function with given fields: e
func (_m *EmployeeRedisService) UpsertEmployee(e model.Employee) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Employee) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertEmployees provides a mock function with given fields: e
func (_m *EmployeeRedisService) UpsertEmployees(e model.Employees) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Employees) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
