// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// EmployeeController is an autogenerated mock type for the EmployeeController type
type EmployeeController struct {
	mock.Mock
}

// CreateEmployee provides a mock function with given fields: w, r
func (_m *EmployeeController) CreateEmployee(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllEmployees provides a mock function with given fields: w, r
func (_m *EmployeeController) GetAllEmployees(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetEmployeeByID provides a mock function with given fields: w, r
func (_m *EmployeeController) GetEmployeeByID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
